# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "app-template-remix"
client_id = "019c4d43be04983e27503561ef16aa4b"
application_url = "https://colleagues-unemployment-autos-promotions.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://colleagues-unemployment-autos-promotions.trycloudflare.com/auth/callback",
  "https://colleagues-unemployment-autos-promotions.trycloudflare.com/auth/shopify/callback",
  "https://colleagues-unemployment-autos-promotions.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "tomotomy.myshopify.com"
